---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s.%(msecs)03d %(name)-12s %(levelname)-8s [%threadName)-12s %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"
    # format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: slacktweet.log
    maxBytes: 10485760 #10MB
    backupCount: 5
    encoding: utf8

  # info-file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: INFO
  #   formatter: simple
  #   filename: info.log
  #   maxBytes: 10485760 #10MB
  #   backupCount: 5
  #   encoding: utf8
  # warning_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: WARNING
  #   formatter: simple
  #   filename: warning.log
  #   maxBytes: 10485760 #10MB
  #   backupCount: 5
  #   encoding: utf8
  # error_file_handler:
  #   class: logging.handlers.RotatingFileHandler
  #   level: ERROR
  #   formatter: simple
  #   filename: errors.log
  #   maxBytes: 10485760 #10MB
  #   backupCount: 5
  #   encoding: utf8

  loggers:
    "":
      level: DEBUG
      handlers: [console, file_handler]
      propagate: no

  root:
    level: NOTSET
    handlers: [console]
    #handlers [console, info_file_handler, warning_file_handler, error_file_handler]
